version: "3.7"

services:
    # frontend:
    #     build: ./frontend
    #     restart: always
    #     ports:
    #         - 3000:3000
    #     env_file:
    #         - .env
    #     depends_on:
    #         - backend
    #     expose:
    #         - 3000
        
    backend:
        build: ./backend-node
        restart: always
        expose:
            - 8000
        ports:
            - 8000:8000
            - 5555:5555
        depends_on:
            - database
        env_file:
            - .env

    database:
        image: "postgres:alpine3.17"
        restart: always
        expose:
            - 5432
        volumes:
            - ./data-sql:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: hamza
            POSTGRES_PASSWORD: 123

