version: "3.7"

services:

    frontend:
        build: ./frontend
        restart: always
        ports:
            - 3000:3000
        env_file:
            - .env
        depends_on:
            - backend
        
    backend:
        build: ./backend-node
        restart: always
        expose:
            - 3001
        ports:
            - 3001:3001
        depends_on:
            - database
        env_file:
            - .env

    database:
        image: "mongo:4.0.27-xenial"
        restart: always
        expose:
            - 27017
        volumes:
            - ./mongo-data:/data/db
        ports:
            - 27017:27017
